### ISSUE TITLE
一加5，氧系统，android 8.1版本，微信6.7.2，插件失效

### ISSUE THREAD

**Issue by Arkbu** [skyun1314/WeChat-plug-in#37]
消息防撤回，自动抢红包 等都没用。有人遇到这个问题吗？

**Comment by Arkbu** [comment]
03-19 12:25:47.595 I/Xposed  (  699): -----------------
03-19 12:25:47.595 I/Xposed  (  699): Starting Xposed version 90-beta3, compiled for SDK 27
03-19 12:25:47.595 I/Xposed  (  699): Device: ONEPLUS A5000 (OnePlus), Android version 8.1.0 (SDK 27)
03-19 12:25:47.595 I/Xposed  (  699): ROM: ONEPLUS A5000_23_180829
03-19 12:25:47.595 I/Xposed  (  699): Build fingerprint: OnePlus/OnePlus5/OnePlus5:8.1.0/OPM1.171019.011/1808081457:user/release-keys
03-19 12:25:47.595 I/Xposed  (  699): Platform: arm64-v8a, 64-bit binary, system server: yes
03-19 12:25:47.595 I/Xposed  (  699): SELinux enabled: yes, enforcing: yes
03-19 12:25:47.609 I/Xposed  (  699): -----------------
03-19 12:25:47.610 I/Xposed  (  699): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-12 17:51:32.301 I/Xposed  (  699): Detected ART runtime
09-12 17:51:32.304 I/Xposed  (  699): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-12 17:51:32.583 I/Xposed  (  699): Loading modules from /data/app/com.example.wx_plug_in3-T3vl0ZXsmA5F8YbsOYJasw==/base.apk
09-12 17:51:40.533 I/Xposed  (  700): -----------------
09-12 17:51:40.533 I/Xposed  (  700): Starting Xposed version 90-beta3, compiled for SDK 27
09-12 17:51:40.533 I/Xposed  (  700): Device: ONEPLUS A5000 (OnePlus), Android version 8.1.0 (SDK 27)
09-12 17:51:40.533 I/Xposed  (  700): ROM: ONEPLUS A5000_23_180829
09-12 17:51:40.533 I/Xposed  (  700): Build fingerprint: OnePlus/OnePlus5/OnePlus5:8.1.0/OPM1.171019.011/1808081457:user/release-keys
09-12 17:51:40.533 I/Xposed  (  700): Platform: arm64-v8a, 32-bit binary, system server: no
09-12 17:51:40.533 I/Xposed  (  700): SELinux enabled: yes, enforcing: yes
09-12 17:51:40.535 I/Xposed  (  700): -----------------
09-12 17:51:40.535 I/Xposed  (  700): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-12 17:51:41.171 I/Xposed  (  700): Detected ART runtime
09-12 17:51:41.173 I/Xposed  (  700): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-12 17:51:41.365 I/Xposed  (  700): Loading modules from /data/app/com.example.wx_plug_in3-T3vl0ZXsmA5F8YbsOYJasw==/base.apk
09-12 17:51:41.712 I/Xposed  (  700):   Loading class com.example.zhang.myapplication.HookLoader
09-12 17:52:59.118 E/Xposed  ( 4324): java.lang.NoSuchMethodError: com.tencent.mm.storage.RegionCodeDecoder#cqi()#exact
09-12 17:52:59.118 E/Xposed  ( 4324): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at com.android.wechat.ؒ.ؒ.ALLATORIxDEMO(cb:24)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at com.android.wechat.Main.handleLoadPackage(gb:204)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at com.example.zhang.myapplication.Main.NativeinvokeHandleHookMethod(Native Method)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at com.example.zhang.myapplication.HookLoader$1.afterHookedMethod(r:823)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.app.Application.attach(<Xposed>)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1107)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1091)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1011)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5940)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.os.Looper.loop(Looper.java:164)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at android.app.ActivityThread.main(ActivityThread.java:6753)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at java.lang.reflect.Method.invoke(Native Method)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-12 17:52:59.118 E/Xposed  ( 4324): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
09-12 17:54:21.741 E/Xposed  ( 7941): java.lang.NoSuchMethodError: com.tencent.mm.storage.RegionCodeDecoder#cqi()#exact
09-12 17:54:21.741 E/Xposed  ( 7941): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at com.android.wechat.ؒ.ؒ.ALLATORIxDEMO(cb:24)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at com.android.wechat.Main.handleLoadPackage(gb:204)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at com.example.zhang.myapplication.Main.NativeinvokeHandleHookMethod(Native Method)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at com.example.zhang.myapplication.HookLoader$1.afterHookedMethod(r:823)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.app.Application.attach(<Xposed>)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1107)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1091)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1011)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5940)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.os.Looper.loop(Looper.java:164)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at android.app.ActivityThread.main(ActivityThread.java:6753)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at java.lang.reflect.Method.invoke(Native Method)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-12 17:54:21.741 E/Xposed  ( 7941): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by slb116763814** [comment]
@arkbu  不知道能不能和别的插件共存。
还会增加别的功能吗？一键添加附近的人好像没有。
